# Generated by Django 5.1.15 on 2026-03-23 20:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('province', models.CharField(blank=True, default='', max_length=64)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('precipitation_mm', models.FloatField(help_text='Precipitation in millimetres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precipitation', to='dashboard.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('station', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='WaterLevelReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('water_level_m', models.FloatField(help_text='Water level in metres')),
                ('flow_rate_cms', models.FloatField(blank=True, help_text='Flow rate in cubic metres per second', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dashboard.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['station', 'timestamp'], name='dashboard_w_station_42427a_idx')],
                'unique_together': {('station', 'timestamp')},
            },
        ),
    ]
