# Generated by Django 5.1.15 on 2026-03-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('water_level', 'Water Level (m)'), ('flow_rate', 'Flow Rate (m³/s)')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('lt', 'Less than'), ('gte', 'Greater than or equal'), ('lte', 'Less than or equal')], max_length=4)),
                ('threshold', models.FloatField()),
                ('email', models.EmailField(help_text='Email address to notify', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='dashboard.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('message', models.TextField()),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
