# Generated by Django 5.1.15 on 2026-03-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dashboard.station')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
